apiVersion: v1
kind: Service
metadata:
  name: activedirectory-demo
  labels:
    app.kubernetes.io/name: activedirectory-demo
    app.kubernetes.io/component: directory
spec:
  selector:
    app.kubernetes.io/name: activedirectory-demo
  ports:
    - name: ldap
      port: 389
      targetPort: ldap
      protocol: TCP
    - name: ldaps
      port: 636
      targetPort: ldaps
      protocol: TCP

# Made with Bob
